### PR TITLE
Refactoring, add link shortcode, add single template

### PR DESCRIPTION
**Pull request by TurqDevDesign**
There were a few features I needed from this plugin that didn't exist, so I took the liberty of adding them. While working on the features I noticed some code that could be replaced by standard Wordpress functions. Overall, along with minor code changes and reorganization, I've added a [profile_link] tag that links to the respective profile. I've also added a new option to the settings page that allows users to select the template that they'd like to use for single profiles. The help page outlines these two features and how to use them.

**Edit: After having my page stop working all of a sudden, I traced the issue back to the custom template being un-retrievable. Fixed issue.**

**Edit: Integrated recent pulls, tested, and my changes still work perfectly, including the fix for displaying all categories. I also managed to find a couple minor bugs myself, went ahead and squashed 'em.**

### CODE REVIEW

**Comment by adamtootle** [comment]
@TurqDevDesign I've been looking over this for a couple of days. Everything's looking good. One thing I thought we may have to add was support for overriding your template with a theme-provided template, but you already have that. So, nice! One thing though - what would you think about prefixing the theme files with `single-staff-`, rather than `staff_single_`? That way we can follow the WP naming conventions [here](https://codex.wordpress.org/Post_Type_Templates). Other than that I don't think I have any suggestions. And I can even add that if need be. Thanks for the work on this! I'll be pushing an update to the wordpress.org repo once I merge this.

**Comment by TurqDevDesign** [comment]
@adamtootle Oh absolutely, no real reason that should be an issue. Give me like 20-25 minutes, I'll see if I can't get it done.

**Comment by TurqDevDesign** [comment]
@adamtootle One more thing, the single template file name is stored in the database under staff_single_template, would you like that changed to mirror the new file scheme? i.e. staff-single-template, single_staff_template, etc.? or is it alright with you?

**Comment by TurqDevDesign** [comment]
@adamtootle I left the database name the same for now and pushed the changes, if you'd like it changed just let me know. I also left a note on the commit regarding a possible issue that I forgot about, I set a comment about it when I coded the single template setting field. If you find it necessary, we could resolve the issue before the pull, but it'll only affect child themes at this point.

**Comment by adamtootle** [comment]
@TurqDevDesign I think that option name is fine. We should be able to use `get_stylesheet_directory()` ([docs](https://codex.wordpress.org/Function_Reference/get_stylesheet_directory)) to target parent _or_ child themes. `get_template_directory()` does only point to the parent. I'm not aware of any issues that would cause and it should solve the issue that may arise with child themes. I can add that in if you'd like.

**Comment by TurqDevDesign** [comment]
@adamtootle Oh perfect, I don't know how I missed that function before... Then again I did code most of that over the course of only 2 or 3 days xD

**Comment by TurqDevDesign** [comment]
Fixed, now just a quick test and we should be good to go.

**Comment by TurqDevDesign** [comment]
@adamtootle It seems to work perfectly, didn't break anything, I think it's good to go.

**Pull request merged**
